### ISSUE TITLE
Mastery effects are randomized on game load in random mode.

### ISSUE THREAD

**Issue by Pikabyte** [qcwxezda/Starsector-Ship-Mastery-System#3]
I assume this is a bug, because I can't imagine it any other way. However it seems that when loading the game, all mastery effects are randomized. I did have random mode enabled, so I'm not sure if it has to do with that. But I've tried pretty much everything I can think of and nothing seems to fix it. 
Unsure if this could also be a mod conflict, but I'm really not sure what it would be, if so. I'll attach my modlist below anyway, in case it might provide insight.

I guess the part that specifically makes me assume it's a bug rather than an intended feature is because it randomizes on _game load_ rather than save load. Also the fact that there is a randomize button that costs MP that seems completely pointless. I'll also include images of three different game reloads and it changing every time.

```
Additional Console Commands
AdvancedGunneryControl
AITweaks_v1.10.12
Angry Periphery v1.5.02
ApproLight
ArthrsShipsNShit
Ashes of Ohm
Ashes of  The Domain - Cryosleeper Module
Ashes of The Domain - Question Of Loyalty
Ashes of  The Domain- Vaults of Knowledge
Ashes of  The Domain - Virtue Of Society
Ashlib_
Audio Plus
Autosave
BetterVariants
Combat Chatter
Commissioned Crews
Console Commands
Console Galaxy
Dassault-Mikoyan Engineering
DetailedCombatResults
Diable-Avionics
Diktat Enhancement 1.2.2c
Domain Explorarium Expansion0.0.20
Emergent Threats
Emergent Threats-IX Revival
Exotica-Technologies
find_case_mismatches_in_mod_files.py
Fleet Journal
GraphicsLib
GuaranteeRareItems
HMI
Hyperdrive
Indies Expansion Pack
Industrial.Evolution3.3.e
Interesting Portraits Pack
Interstellar Imperium
Iron Shell 1.183aj
Knights of Ludd
Ko_Combine
Larger Zoom Out
LazyLib
Leading Pip
Logistics Notifications
LOST_SECTOR-0.6.2d
Luddic_Enhancement
Luddic_Enhancement_IED
LunaLib
MagicLib
Marvelous-Personas-v1.2.1
MoreBarMissions
More Combat Terrain Effects
New Beginnings
Nexerelin
Nomadic.Survival
Officer.Extension
PAGSM v1.14.1
Particle Engine
Perilous Expanse
Persean-Chronicles-3.0.9
PlanetSearch
PortraitChanger
prv Agni
prv Library
Random-Assortment-of-Things
RetroLib
Roider Union
Rouge
Ruthless Sector
SecondInCommand
Secrets of the Frontier 0.14.2c
Ship and Weapon Pack
Ship Mastery System
ShowFleetDP
sicdustkeeper
SpaceTruckin [v1.4a]
SpeedUp
SS-armaa-3.0.6
Starlords-0.3.2
starpocalypse
Starship Legends
stelnet
Substance.Abuse1.1.c
System_Marker
TakeNoPrisoners
tasc
UAF
Underworld
Unknown Skies
UnofficialNewGamePlus
VariantsLib
VayraMerged
VIC
Volantian Reclamation Initiative
WeaponArcs
WhichMod
WhichTMI-1.2.0
```
![FnY1YxX](https://github.com/user-attachments/assets/a4746ffa-2c93-44c2-9d79-d63cfe4a9860)
![fT58HGn](https://github.com/user-attachments/assets/fb826550-4980-4eda-bbf0-63e4cec6a7e9)
![i67gys7](https://github.com/user-attachments/assets/30ffed8c-cb79-48a3-9f2b-8ea1480491d9)

**Comment by qcwxezda** [comment]
What version of the mod are you using? There was an issue in a previous version but that should have been resolved in 0.11.3, with the following patch note: 
- Fixed S-mod capacity levels being unseeded when random mode is enabled.

The relevant commit is [here](https://github.com/qcwxezda/Starsector-Ship-Mastery-System/commit/e641841be6741c1e9c664cba67cfc673103af933#diff-31060e1ada4dad27766683b9fa1a06a3411abecdfdbb3b12f7508f68d812eb5eR440-R442). 

Please let me know if you're still having issues with the latest version of this mod.

**Comment by Pikabyte** [comment]
I was using 0.11.4 (I haven't actually played the game yet since 0.11.5 came out)

EDIT: Though thinking about it, I could have been usiing 0.11.2 when I had started my save. Would 0.11.3 have fixed it retroactively on a previous save?

**Comment by qcwxezda** [comment]
Are you able to replicate the bug with version 0.11.3+? Mastery effects are regenerated when necessary (so, when loading, they are only regenerated if you rerolled or if you're loading a save with a different commander id), so it should be pretty easy to test by just loading in, making note of what masteries your ships have, exiting the game, and then restarting and loading in again.

**Comment by Pikabyte** [comment]
The images I posted were all taken on 0.11.4, as I said. It's possible that I had been using 0.11.2 at the start of the save, but when I noticed those issues I updated to the latest version at the time (which was 0.11.4), and they still occured. Unsure if I would have had to start a new save to get it fixed, but I didn't really want to do that.

**Comment by qcwxezda** [comment]
I'm asking if you can replicate the issue *now* on a recent version, because I'm not able to. Not to mention, if you updated from 0.11.2 to 0.11.4, your mastery effects would have changed anyway because the weighting system was changed.

Edit: You posted those exact same images on Discord on 12/27/2024 9:55AM EST, meanwhile I uploaded the 0.11.4 patch two days later:
![image](https://github.com/user-attachments/assets/910adab2-7d7c-4a86-a930-c357ffb1ccd4)
Forget Starsector mods, how much do you want for your time machine?

**Comment by Pikabyte** [comment]
Sorry, maybe I should have clarified. Those pictures may not have been from the 0.11.4 patch, but I _did_ test with the 0.11.4 patch. After taking those pictures, and it still occured.

I suppose I'll try it again with the 0.11.5 patch today on the same save, and give an update.

EDIT: Ok so idk why but for some reason I can't load the save... im not sure if 0.11.5 was save incompatible but whatever. I *do* know for a fact that I tested 0.11.4, as that what was in my mods folder before I replaced it with 0.11.5. 

The reason the save was important was because I'm not sure if the issue was specific to that save, and I didn't really want to start a new save anyway. I haven't tested it in a new save, but I'll just assume it's fixed for all new saves I guess, since I assume that's the way everyone else had been testing it, and close this. Apologies, I just kinda don't feel like doing a bunch of debugging at the moment, and took a relatively short break from playing it anyway. Feel free to close this as fixed if you want.

**Comment by qcwxezda** [comment]
There shouldn't be any save compatibilities between existing versions of this mod. Can you post the stack trace you get when loading the save? It should be located at the bottom of starsector.log after you fail to load.
